Use yowasp_yosys instead of system-installed yosys
SymbiFlow/sphinxcontrib-verilog-diagrams pull request #50
Opened 2020-08-05 15:43 UTC by daniellimws

Following the discussion in #40, change to use the wasm-bundled version of yosys as in [yowasp_yosys](https://github.com/YoWASP/yosys) instead of the system-installed yosys (symbiflow projects use conda to install it, but this might not be the case for other users).

One benefit of this is that it allows us to control the version of yosys used by the user. This is important because there might be breaking changes in yosys, such as #13, and it wouldn't be ideal to cater for multiple versions of yosys.

One small downside is this takes about twice the duration compared to native yosys but I don't think this really matters.

Signed-off-by: Daniel Lim Wee Soong <weesoong.lim@gmail.com>

2020-08-05 16:06 UTC, mithro commented
Can we make this a configuration option?

2020-08-05 16:10 UTC, daniellimws commented
Yup sure, so a setting in conf.py?

2020-08-05 19:34 UTC, mithro commented
Yeap! Sounds good.

2020-08-09 06:27 UTC, daniellimws commented
Now we support both types of yosys installations. @mithro Do you think we need to implement tests for both use cases? I can't think of any straightforward way of doing so without setting up a whole sphinx project for each of the two cases.

2020-08-09 21:22 UTC, mithro commented
@daniellimws - Can we just set up travis to run in the two configurations?

2020-08-10 15:33 UTC, daniellimws commented
@mithro I'm not good with Travis so if you got any ideas you could try it first

2020-08-27 11:32 UTC, rw1nkler commented
I believe that the mechanism for tests provided in the #52 can be useful here.

2020-09-01 15:50 UTC, mithro commented
@rw1nkler -- Can you take a look at this PR? If @daniellimws doesn't currently have the time, can you take it over and get it merged?

2020-09-01 15:53 UTC, daniellimws commented
Hi, yes I currently am quite busy with school work. I might be free next week though. Feel free to take over if you want :).

2020-09-08 08:57 UTC, rw1nkler requested changes
I left my comments below, they are addressed in the #55

2020-09-08 10:35 UTC, rw1nkler requested changes

2020-09-08 10:35 UTC, rw1nkler commented on README.rst
> +      VerilogDiagram.use_yowasp = False
In my opinion, the global settings for the extension should be based on variables added to sphinxconf.py file.
See: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_config_value

2020-09-08 10:35 UTC, rw1nkler commented on sphinxcontrib_verilog_diagrams/__init__.py
> +prep -top {top} {flatten}; cd {top}; write_json -compat-int {ojson}
The compatibility mode seems to work incorectly when added to the standard conda Yosys version.

2020-09-14 09:08 UTC, closed without merging